apiVersion: v1
kind: Service
metadata:
  name: sysmetric
  namespace: sysmetric

spec:
  type: NodePort

  selector:
    app: sysmetric

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
